# Generated by Django 4.2.8 on 2026-02-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroCarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_data",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="Файл изображения"
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME-тип"
                    ),
                ),
                (
                    "image_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя файла"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подпись (alt)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение карусели Hero",
                "verbose_name_plural": "Карусель Hero",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image_data",
                    models.BinaryField(blank=True, null=True, verbose_name="Файл фото"),
                ),
                (
                    "image_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME-тип"
                    ),
                ),
                (
                    "image_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя файла"
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, verbose_name="Ссылка «Подробнее»"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="Адрес"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image_data",
                    models.BinaryField(blank=True, null=True, verbose_name="Файл фото"),
                ),
                (
                    "image_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME-тип"
                    ),
                ),
                (
                    "image_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя файла"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo_data",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="Файл логотипа"
                    ),
                ),
                (
                    "logo_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME-тип"
                    ),
                ),
                (
                    "logo_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя файла"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
    ]
