# Generated by Django 4.2.8 on 2026-02-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_gold",
                    models.CharField(
                        default="#D4AF37",
                        help_text="HEX формат, например: #D4AF37",
                        max_length=7,
                        verbose_name="Основной золотой цвет",
                    ),
                ),
                (
                    "primary_dark",
                    models.CharField(
                        default="#1A1A1A",
                        help_text="HEX формат",
                        max_length=7,
                        verbose_name="Основной темный цвет",
                    ),
                ),
                (
                    "secondary_blue",
                    models.CharField(
                        default="#0A2540",
                        help_text="HEX формат",
                        max_length=7,
                        verbose_name="Вторичный синий цвет",
                    ),
                ),
                (
                    "accent_purple",
                    models.CharField(
                        default="#695EF9",
                        help_text="HEX формат",
                        max_length=7,
                        verbose_name="Акцентный фиолетовый цвет",
                    ),
                ),
                (
                    "bg_light",
                    models.CharField(
                        default="#F8FAFC",
                        help_text="HEX формат",
                        max_length=7,
                        verbose_name="Светлый фон",
                    ),
                ),
                (
                    "bg_lavender",
                    models.CharField(
                        default="#F0EFFF",
                        help_text="HEX формат",
                        max_length=7,
                        verbose_name="Лавандовый фон",
                    ),
                ),
                (
                    "white",
                    models.CharField(
                        default="#FFFFFF",
                        help_text="HEX формат",
                        max_length=7,
                        verbose_name="Белый цвет",
                    ),
                ),
                (
                    "text_dark",
                    models.CharField(
                        default="#0A0D12",
                        help_text="HEX формат",
                        max_length=7,
                        verbose_name="Темный текст",
                    ),
                ),
                (
                    "text_body",
                    models.CharField(
                        default="#0A0D12",
                        help_text="HEX формат",
                        max_length=7,
                        verbose_name="Цвет основного текста",
                    ),
                ),
                (
                    "text_light",
                    models.CharField(
                        default="#64748B",
                        help_text="HEX формат",
                        max_length=7,
                        verbose_name="Светлый текст",
                    ),
                ),
                (
                    "text_muted",
                    models.CharField(
                        default="#A4A7AE",
                        help_text="HEX формат",
                        max_length=7,
                        verbose_name="Приглушенный текст",
                    ),
                ),
                (
                    "font_primary",
                    models.CharField(
                        default="Inter, sans-serif",
                        help_text="Например: Inter, sans-serif или Arial, sans-serif",
                        max_length=100,
                        verbose_name="Основной шрифт",
                    ),
                ),
                (
                    "font_heading",
                    models.CharField(
                        default="Inter, sans-serif",
                        help_text="Например: DejaVu Sans, sans-serif",
                        max_length=100,
                        verbose_name="Шрифт заголовков",
                    ),
                ),
                (
                    "heading_xl",
                    models.PositiveIntegerField(
                        default=44, verbose_name="Размер заголовка XL (px)"
                    ),
                ),
                (
                    "heading_xl_lh",
                    models.PositiveIntegerField(
                        default=52, verbose_name="Высота строки заголовка XL (px)"
                    ),
                ),
                (
                    "heading_lg",
                    models.PositiveIntegerField(
                        default=24, verbose_name="Размер заголовка LG (px)"
                    ),
                ),
                (
                    "heading_lg_lh",
                    models.PositiveIntegerField(
                        default=28, verbose_name="Высота строки заголовка LG (px)"
                    ),
                ),
                (
                    "body_lg",
                    models.PositiveIntegerField(
                        default=18, verbose_name="Размер текста LG (px)"
                    ),
                ),
                (
                    "body_lg_lh",
                    models.PositiveIntegerField(
                        default=24, verbose_name="Высота строки текста LG (px)"
                    ),
                ),
                (
                    "body",
                    models.PositiveIntegerField(
                        default=16, verbose_name="Размер основного текста (px)"
                    ),
                ),
                (
                    "body_lh",
                    models.PositiveIntegerField(
                        default=22, verbose_name="Высота строки основного текста (px)"
                    ),
                ),
                (
                    "body_sm",
                    models.PositiveIntegerField(
                        default=14, verbose_name="Размер малого текста (px)"
                    ),
                ),
                (
                    "body_sm_lh",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Высота строки малого текста (px)"
                    ),
                ),
                (
                    "spacing_xs",
                    models.PositiveIntegerField(
                        default=8, verbose_name="Отступ XS (px)"
                    ),
                ),
                (
                    "spacing_sm",
                    models.PositiveIntegerField(
                        default=16, verbose_name="Отступ SM (px)"
                    ),
                ),
                (
                    "spacing_md",
                    models.PositiveIntegerField(
                        default=24, verbose_name="Отступ MD (px)"
                    ),
                ),
                (
                    "spacing_lg",
                    models.PositiveIntegerField(
                        default=40, verbose_name="Отступ LG (px)"
                    ),
                ),
                (
                    "spacing_xl",
                    models.PositiveIntegerField(
                        default=64, verbose_name="Отступ XL (px)"
                    ),
                ),
                (
                    "header_height",
                    models.PositiveIntegerField(
                        default=72, verbose_name="Высота шапки (px)"
                    ),
                ),
                (
                    "button_min_height",
                    models.PositiveIntegerField(
                        default=44, verbose_name="Минимальная высота кнопки (px)"
                    ),
                ),
                (
                    "button_padding_h",
                    models.PositiveIntegerField(
                        default=24, verbose_name="Горизонтальный отступ кнопки (px)"
                    ),
                ),
                (
                    "button_padding_v",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Вертикальный отступ кнопки (px)"
                    ),
                ),
                (
                    "border_radius",
                    models.PositiveIntegerField(
                        default=8, verbose_name="Радиус скругления (px)"
                    ),
                ),
                (
                    "border_radius_lg",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Большой радиус скругления (px)"
                    ),
                ),
                (
                    "shadow_sm",
                    models.CharField(
                        default="0 2px 8px rgba(0,0,0,0.06)",
                        help_text="CSS значение box-shadow",
                        max_length=100,
                        verbose_name="Маленькая тень",
                    ),
                ),
                (
                    "shadow_md",
                    models.CharField(
                        default="0 8px 24px rgba(0,0,0,0.1)",
                        help_text="CSS значение box-shadow",
                        max_length=100,
                        verbose_name="Средняя тень",
                    ),
                ),
                (
                    "shadow_lg",
                    models.CharField(
                        default="0 16px 92px -4px rgba(27, 30, 27, 0.10)",
                        help_text="CSS значение box-shadow",
                        max_length=100,
                        verbose_name="Большая тень",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка для Полины",
                "verbose_name_plural": "Настройка для Полины",
            },
        ),
    ]
