# Generated by Django 4.2.8 on 2026-02-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_designsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_name",
                    models.CharField(
                        help_text="Например: Заголовок Hero, Подзаголовок Hero",
                        max_length=255,
                        verbose_name="Название элемента",
                    ),
                ),
                (
                    "css_selector",
                    models.CharField(
                        help_text="Например: .hero__title или #hero-title",
                        max_length=255,
                        unique=True,
                        verbose_name="CSS селектор",
                    ),
                ),
                (
                    "font_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Текущий размер. Оставьте пустым для значения по умолчанию.",
                        null=True,
                        verbose_name="Размер шрифта (px)",
                    ),
                ),
                (
                    "font_size_min",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Для clamp() или min()",
                        null=True,
                        verbose_name="Минимальный размер (px)",
                    ),
                ),
                (
                    "font_size_max",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Для clamp() или max()",
                        null=True,
                        verbose_name="Максимальный размер (px)",
                    ),
                ),
                (
                    "font_weight",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Например: 400, 600, 700, bold",
                        max_length=50,
                        verbose_name="Толщина шрифта",
                    ),
                ),
                (
                    "line_height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Высота строки (px)"
                    ),
                ),
                (
                    "letter_spacing",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Например: 0.02em, 2px",
                        max_length=20,
                        verbose_name="Межбуквенное расстояние",
                    ),
                ),
                (
                    "margin_top",
                    models.IntegerField(
                        blank=True,
                        help_text="Отрицательные значения допустимы",
                        null=True,
                        verbose_name="Отступ сверху (px)",
                    ),
                ),
                (
                    "margin_bottom",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Отступ снизу (px)"
                    ),
                ),
                (
                    "margin_left",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Отступ слева (px)"
                    ),
                ),
                (
                    "margin_right",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Отступ справа (px)"
                    ),
                ),
                (
                    "padding_top",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Внутренний отступ сверху (px)",
                    ),
                ),
                (
                    "padding_bottom",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Внутренний отступ снизу (px)",
                    ),
                ),
                (
                    "padding_left",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Внутренний отступ слева (px)",
                    ),
                ),
                (
                    "padding_right",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Внутренний отступ справа (px)",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "По умолчанию"),
                            ("relative", "Relative"),
                            ("absolute", "Absolute"),
                            ("fixed", "Fixed"),
                            ("sticky", "Sticky"),
                        ],
                        default="",
                        help_text="CSS position",
                        max_length=20,
                        verbose_name="Позиционирование",
                    ),
                ),
                (
                    "top",
                    models.IntegerField(
                        blank=True,
                        help_text="Для position: absolute/fixed",
                        null=True,
                        verbose_name="Сверху (px)",
                    ),
                ),
                (
                    "left",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Слева (px)"
                    ),
                ),
                (
                    "right",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Справа (px)"
                    ),
                ),
                (
                    "bottom",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Снизу (px)"
                    ),
                ),
                (
                    "z_index",
                    models.IntegerField(
                        blank=True, default=None, null=True, verbose_name="Z-index"
                    ),
                ),
                (
                    "width",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Например: 100%, 500px, auto",
                        max_length=50,
                        verbose_name="Ширина",
                    ),
                ),
                (
                    "max_width",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Например: 800px, 100%",
                        max_length=50,
                        verbose_name="Максимальная ширина",
                    ),
                ),
                (
                    "min_width",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Минимальная ширина",
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Например: 100px, auto",
                        max_length=50,
                        verbose_name="Высота",
                    ),
                ),
                (
                    "max_height",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Максимальная высота",
                    ),
                ),
                (
                    "min_height",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Минимальная высота",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HEX формат, например: #000000",
                        max_length=7,
                        verbose_name="Цвет текста",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HEX формат",
                        max_length=7,
                        verbose_name="Цвет фона",
                    ),
                ),
                (
                    "text_align",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "По умолчанию"),
                            ("left", "Слева"),
                            ("center", "По центру"),
                            ("right", "Справа"),
                            ("justify", "По ширине"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Выравнивание текста",
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Любые дополнительные CSS свойства. Например: transform: scale(1.1);",
                        verbose_name="Дополнительный CSS",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Для сортировки в админке",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Применить эти настройки",
                        verbose_name="Активно",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка элемента",
                "verbose_name_plural": "Настройки элементов",
                "ordering": ["order", "element_name"],
            },
        ),
    ]
