# Generated by Django 4.2.8 on 2026-02-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_elementsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="elementsettings",
            name="selector_type",
            field=models.CharField(
                choices=[
                    ("tag", "HTML тег (h1, p, span, header, footer и т.д.)"),
                    ("class", "CSS класс (.hero__title)"),
                    ("id", "CSS ID (#hero-title)"),
                    ("custom", "Произвольный селектор"),
                ],
                default="class",
                help_text="Выберите тип элемента для редактирования",
                max_length=20,
                verbose_name="Тип селектора",
            ),
        ),
        migrations.AlterField(
            model_name="elementsettings",
            name="css_selector",
            field=models.CharField(
                help_text="Например: h1, p, span, .hero__title, #hero-title, header, footer, section",
                max_length=255,
                unique=True,
                verbose_name="CSS селектор",
            ),
        ),
        migrations.AlterField(
            model_name="elementsettings",
            name="element_name",
            field=models.CharField(
                help_text="Например: Заголовок Hero, Подзаголовок Hero, Все параграфы",
                max_length=255,
                verbose_name="Название элемента",
            ),
        ),
    ]
