# Generated by Django 4.2.8 on 2026-02-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_elementsettings_selector_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designsettings",
            name="accent_purple",
            field=models.CharField(
                default="#7C3AED",
                help_text="HEX формат",
                max_length=7,
                verbose_name="Акцентный фиолетовый цвет",
            ),
        ),
        migrations.AlterField(
            model_name="designsettings",
            name="border_radius",
            field=models.PositiveIntegerField(
                default=12, verbose_name="Радиус скругления (px)"
            ),
        ),
        migrations.AlterField(
            model_name="designsettings",
            name="text_body",
            field=models.CharField(
                default="#0F172A",
                help_text="HEX формат",
                max_length=7,
                verbose_name="Цвет основного текста",
            ),
        ),
        migrations.AlterField(
            model_name="designsettings",
            name="text_dark",
            field=models.CharField(
                default="#0F172A",
                help_text="HEX формат",
                max_length=7,
                verbose_name="Темный текст",
            ),
        ),
    ]
