# Generated by Django 4.2.8 on 2026-02-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_designsettings_accent_purple_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elementsettings",
            name="element_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Например: Заголовок Hero, Подзаголовок Hero, Все параграфы",
                max_length=255,
                verbose_name="Название элемента",
            ),
        ),
    ]
