# Generated by Django 4.2.8 on 2026-02-01 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_elementsettings_element_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название (RU)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название (EN)"
                    ),
                ),
                (
                    "name_de",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название (DE)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("project", "Проект"),
                            ("consult", "Консультация"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Причина обращения",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В процессе"),
                            ("closed", "Закрыта"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message_admin",
                    models.TextField(blank=True, verbose_name="Ответ администратора"),
                ),
                (
                    "admin_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID администратора"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка в поддержку",
                "verbose_name_plural": "Заявки в поддержку",
                "db_table": "contact_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Код проекта"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирован"),
                            ("in_progress", "В работе"),
                            ("completed", "Завершен"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(blank=True, null=True, verbose_name="Год"),
                ),
                (
                    "type",
                    models.CharField(blank=True, max_length=100, verbose_name="Тип"),
                ),
                (
                    "size",
                    models.CharField(blank=True, max_length=100, verbose_name="Размер"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=50, verbose_name="Цвет"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект (админка)",
                "verbose_name_plural": "Проекты (админка)",
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
    ]
