# Generated by Django 4.2.8 on 2026-02-02 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_category_contactrequest_adminproject"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название (RU)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название (EN)"
                    ),
                ),
                (
                    "name_de",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название (DE)"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="например: it, bau", unique=True, verbose_name="Код"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория заявки",
                "verbose_name_plural": "Категории заявок",
                "db_table": "request_categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="contactrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Сообщение в поддержку",
                "verbose_name_plural": "Поддержка",
            },
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("support", "Поддержка"),
                    ("project", "Проект"),
                    ("consult", "Консультация"),
                    ("other", "Другое"),
                ],
                default="support",
                max_length=20,
                verbose_name="Причина",
            ),
        ),
        migrations.CreateModel(
            name="RequestSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название (RU)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название (EN)"
                    ),
                ),
                (
                    "name_de",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название (DE)"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="например: registration, it_profile",
                        verbose_name="Код",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="main.requestcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория заявки",
                "verbose_name_plural": "Подкатегории заявок",
                "db_table": "request_subcategories",
                "ordering": ["order", "name"],
                "unique_together": {("category", "slug")},
            },
        ),
        migrations.CreateModel(
            name="RequestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.CharField(max_length=255, verbose_name="Текст вопроса"),
                ),
                (
                    "question_text_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Текст (EN)"
                    ),
                ),
                (
                    "question_text_de",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Текст (DE)"
                    ),
                ),
                (
                    "field_name",
                    models.SlugField(
                        help_text="например: company_name", verbose_name="Имя поля"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="main.requestsubcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос заявки",
                "verbose_name_plural": "Вопросы заявок",
                "db_table": "request_questions",
                "ordering": ["order", "question_text"],
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "extra_answers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON: поле -> ответ",
                        verbose_name="Ответы на вопросы",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В процессе"),
                            ("closed", "Закрыта"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message_admin",
                    models.TextField(blank=True, verbose_name="Ответ администратора"),
                ),
                (
                    "admin_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID администратора"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="main.requestcategory",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="main.requestsubcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "db_table": "requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
