# Generated by Django 4.2.8 on 2026-02-02 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0009_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cabinet_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.CreateModel(
            name="RequestStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("history", "История заявки"),
                            ("project", "Этапы проекта"),
                        ],
                        default="history",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="main.request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этап заявки",
                "verbose_name_plural": "Этапы заявок",
                "db_table": "request_stages",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
