# Generated by Django 4.2.8 on 2026-02-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_cabinet_request_user_stages"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Аватар"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("client", "Клиент"),
                    ("company", "Компания"),
                    ("worker", "Работник"),
                ],
                default="client",
                max_length=20,
                verbose_name="Тип",
            ),
        ),
    ]
