# Generated by Django 4.2.8 on 2026-02-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_add_userprofile_avatar"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="adminproject",
            index=models.Index(fields=["status"], name="projects_status_6303d7_idx"),
        ),
        migrations.AddIndex(
            model_name="adminproject",
            index=models.Index(
                fields=["-created_at"], name="projects_created_390fdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(fields=["status"], name="contact_req_status_03775e_idx"),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["-created_at"], name="contact_req_created_461a42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["status"], name="requests_status_58d546_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["-created_at"], name="requests_created_7f688f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["category", "status"], name="requests_categor_5e4933_idx"
            ),
        ),
    ]
