# Generated by Django 4.2.8 on 2026-02-02 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0012_add_model_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Для аналитики",
                max_digits=12,
                null=True,
                verbose_name="Сумма",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новая"),
                    ("in_progress", "В обработке"),
                    ("approved", "Одобрена"),
                    ("rejected", "Отклонена"),
                    ("closed", "Закрыта"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.CreateModel(
            name="UserTwoFA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("sms", "SMS"), ("telegram", "Telegram")],
                        default="sms",
                        max_length=20,
                        verbose_name="Метод",
                    ),
                ),
                (
                    "phone_or_username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Телефон или @username"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="Включено"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_fa",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "2FA пользователя",
                "verbose_name_plural": "2FA пользователей",
                "db_table": "user_two_fa",
            },
        ),
    ]
