# Generated by Django 4.2.8 on 2026-02-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_cabinet_analytics_and_2fa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_data",
            field=models.BinaryField(
                blank=True, null=True, verbose_name="Файл аватара"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Имя файла"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_type",
            field=models.CharField(blank=True, max_length=100, verbose_name="MIME-тип"),
        ),
    ]
